sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: czk #实验室密码为czk 笔记本密码为czk520
  # 阿里云OSS相关配置
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEEzP9UFrL9U8FSbjjR
    access-key-secret: zlzKK4lqc1eYFmhTM7pPkfQJBBuFyP
    bucket-name: sky-take-out-czk

